name: Reusable ACR Build and Push workflow
on:
    workflow_call:
      inputs:
        env-name:
          required: true
          type: string
        acr-name:
          required: true
          type: string
        image-name:
          required: true
          type: string
        app-folder-path:
          required: true
          type: string
      

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ${{inputs.env-name}}
        steps:
        - name: Log in to Azure with sevice principal
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Log in Azure Container Registry
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
               az acr login --name ${{inputs.acr-name}}
        - name: Build and Push to ACR
          run: |
            echo "Building image [${{ inputs.image-name }}] and environment [${{ inputs.env-name }}]"
            cd ${{ inputs.app-folder-path }}
            docker build . -t ${{inputs.acr-name}}.azurecr.io/${{inputs.image-name}}:${{github.sha}}
            docker push ${{inputs.acr-name}}.azurecr.io/${{inputs.image-name}}:${{github.sha}}
            echo "image successfully pushed: ${{inputs.acr-name}}.azurecr.io/${{inputs.image-name}}:${{github.sha}}